function pi = busincfun(theta,k,le,n,r,w,gamma,vi,delta)
%-------------------------------------------------------------------------%
% DESCRIPTION:
% This function returns the business income generated by a self-employed
%
% INPUTS:
% theta:  entrepreneurial ability
% k,le,n: capital, labor supply, labor hirings
% r,w,gamma,vi,delta: other parameters
%
% OUTPUTS:
% pi: business income
%
% EXTERNAL FILES:
% + prodfun.m
%
% NOTES:
% Updated by Alessandro Di Nola on September 18, 2020.
%-------------------------------------------------------------------------%

pi = theta.*prodfun(k,le,n,gamma,vi)-delta*k-r*k-w*n;

end %end function busincfun
